### ISSUE TITLE
Server related infrastructure

### ISSUE THREAD

**Issue by narqo** [substack/substack-flavored-webapp#3]
Hey @substack, I couldn't find any better way to ask you about related post in your blog, than through the github issues ;)

My questions are:

1) What do you use to cluster your application? Does `tcp-bind` works fine with node.js cluster? Will child processes inherit master's uid/gid?

2) How do you supervise node's process? 

~~~
$ sudo node server.js -u $USER -g $USER
~~~

What happens if web server been rebooted (I mean OS itself)? How do you upgrade application code in the production, as you need to restart master process after the has been upgraded?

**Comment by substack** [comment]
I'm not running anything super critical so I just run the server process like this inside of a screen:

``` sh
while true; do sudo node server.js -u $USER -g $USER; echo '**** CRASHED '`date`' ****'; done
```

and I don't have any scripts that spin up when the system boots but I've done that with init scripts and `update-rc.d` before.

I don't have anything that gets enough traffic to need multiple instances of the server, but I would rather do that with a load balancer proxy in front of webapps on several servers than with the core cluster library.
